<?php

function pet_menu()
{
     $abeer= array();
     $abeer['pets']= array(
         'title' => "My Pets!",
         'page callback' => 'pets_display',
         'access callback' => TRUE,
         'type' => MENU_NORMAL_ITEM,
     );
    return $abeer;
 }


  function pets_display(){
          return '<img src="https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRwpH5pAd9JmnZkCToVWKtmLXr8TYuc5rcZFCdawCsuyWVUTuY7"><p>Pet Name: nano
              <br/>Pet Age :10
              <br/>Pet Type: Cat</p>
              <a href="/farewell">Bye</a>';
  }
