<?php
function greeting_menu() {
    $items = array();

    $items['hello_friend'] = array(
        'title' => "Hello Abeer!",
        'page callback' => 'say_hello',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );


    $items['farewell'] = array(
        'title' => 'Farewell Friend!',
        'page callback' => 'say_farewell',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    return $items;
}

function say_hello() {
    return '<p>Hello my dear friend chitra!</p>';
}
function say_farewell() {
    return '<p>fare thee well my dear friend chitra!</p>';
}
